### ISSUE TITLE
Pascal's Triangle - Adobe

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#52] opened 2022-12-05 07:52 UTC
https://leetcode.com/problems/pascals-triangle/

**Comment by SattyamSamania** [comment] 2022-12-05 14:19
Hey @shelcia can you please specify what to do in this issue so that i can get the clarity ?

**Comment by shelcia** [comment] 2022-12-05 16:53
You will have to add the program in new page

**Comment by yashhkataria** [comment] 2022-12-05 17:49
If the issue is still unresolved, please assign it to me

**Closed** 2022-12-08 13:14 UTC
Labels: easy, codepeak22
